# Generated by Django 5.0.4 on 2024-04-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='garden',
            field=models.ManyToManyField(to='garden.garden'),
        ),
    ]
