# Generated by Django 5.0.7 on 2024-08-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_remove_garden_events_event_garden'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantlocation',
            name='condition',
            field=models.CharField(blank=True, help_text='Condition of the plant at the location.', max_length=255),
        ),
        migrations.AddField(
            model_name='plantlocation',
            name='exsicata_image_url',
            field=models.URLField(blank=True, help_text='URL to the digitalized image of the exsicata.'),
        ),
        migrations.AddField(
            model_name='plantlocation',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL to an image of the plant at this location.'),
        ),
        migrations.AddField(
            model_name='plantlocation',
            name='notes',
            field=models.TextField(blank=True, help_text="Additional notes about the plant's location."),
        ),
        migrations.AddField(
            model_name='plantlocation',
            name='qr_code_url',
            field=models.URLField(blank=True, help_text='URL to the QR code image or data.'),
        ),
        migrations.AlterField(
            model_name='plantlocation',
            name='cod',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
