# Generated by Django 5.0.1 on 2024-01-22 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botanic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the family.'),
        ),
        migrations.AddField(
            model_name='genus',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the genus.'),
        ),
        migrations.AddField(
            model_name='species',
            name='average_height',
            field=models.FloatField(blank=True, help_text='Average height of the species.', null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='blooming_season',
            field=models.CharField(blank=True, help_text='Blooming season of the species.', max_length=50),
        ),
        migrations.AddField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the species.'),
        ),
        migrations.AddField(
            model_name='species',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the representative image of the species.'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the collection.'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(help_text='Name of the collection.', max_length=255),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(help_text='Name of the family.', max_length=255),
        ),
        migrations.AlterField(
            model_name='genus',
            name='family',
            field=models.ForeignKey(help_text='Family to which the genus belongs.', on_delete=django.db.models.deletion.CASCADE, to='botanic.family'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='name',
            field=models.CharField(help_text='Name of the genus.', max_length=255),
        ),
        migrations.AlterField(
            model_name='species',
            name='collections',
            field=models.ManyToManyField(blank=True, help_text='Collections to which the species belongs.', to='botanic.collection'),
        ),
        migrations.AlterField(
            model_name='species',
            name='genus',
            field=models.ForeignKey(help_text='Genus to which the species belongs.', on_delete=django.db.models.deletion.CASCADE, to='botanic.genus'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(help_text='Name of the species.', max_length=255),
        ),
    ]
